spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/spring-cloud
    username: postgres
    password: postgre

eureka:
  client:
    sevice-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

server:
  port: 8081