spring:
  application:
    name: users-server
#  profiles:
#    active: default
  config:
    import: optional:configserver:http://localhost:8888

management:
  endpoint:
    info:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    com.revolut.persons.client.NoteClient: DEBUG