#spring.application.name=gateway-server
#spring.config.import=optional:configserver:http://localhost:8888
#
#spring.cloud.gateway.routes[0].id=users-getAll
#spring.cloud.gateway.routes[0].uri=lb://users-server
#spring.cloud.gateway.routes[0].predicates[0]=Path=/users
#spring.cloud.gateway.routes[0].predicates[1]=Method=GET
#spring.cloud.gateway.routes[0].predicates[2]=Header=Authorization, Bearer (.*)
#spring.cloud.gateway.routes[0].filters[0]=RemoveRequestHeader=Cookie
#spring.cloud.gateway.routes[0].filters[1]=RewritePath=/users, /users
#spring.cloud.gateway.routes[1].id=users-getOne
#spring.cloud.gateway.routes[1].uri=lb://users-server
#spring.cloud.gateway.routes[1].predicates[0]=Path=/getUser/1
#spring.cloud.gateway.routes[1].predicates[1]=Method=GET
#spring.cloud.gateway.routes[1].filters[0]=RemoveRequestHeader=Cookie
#spring.cloud.gateway.routes[1].filters[1]=RewritePath=/getUser/1, /users/getUser/1
token:
  secret: 1234qwer5678tyui
spring:
  application:
    name: gateway-server
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    gateway:
      routes:
        - id: users-status-check
          uri: lb://users-server
          predicates:
            - Path=/users-server/users/status/check
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-server/(?<segment>.*), /$\{segment}
            - AuthorizationHeaderFilter
#         getAll
        - id: users-get-all
          uri: lb://users-server
          predicates:
            - Path=/users-server/users
            - Method=GET
            - Header=Authorization, Bearer (.*)
          filters:
            - AuthorizationHeaderFilter
            - RemoveRequestHeader=Cookie
            - RewritePath=/users-server/(?<segment>.*), /$\{segment}
#        - id: users-create
#          uri: lb://users-server
#          predicates:
#            - Path=/users/createUser
#            - Method=POST
#            - Header=Authorization, Bearer (.*)
#          filters:
#            - RemoveRequestHeader=Cookie
#            - RewritePath=/users/createUser, /createUser
#            - AuthorizationHeaderFilter
#        - id: users-get-update-delete
#          uri: lb://users-server
#          predicates:
#            - Path=/users/**
#            - Method=GET,PATCH,PUT,DELETE
#          filters:
#            - RemoveRequestHeader=Cookie
#            - AuthorizationHeaderFilter