spring:
  application:
    name: notes
  profiles:
    active: dev
  config:
    import: optional:configserver:http://localhost:8888

resilience4j:
  circuitbreaker:
    instances:
      persons:
        properties:
          minimumNumberOfCalls: 500
feign:
  circuitbreaker:
    enabled: true
