server:
  port: 8888

spring:
  application:
    name: config-server
  profiles:
    active: native, git
  cloud:
    config:
      fail-fast: true
      discovery.enabled: true
      server:
        native:
          search-locations: file:\\\Users\r.kholodnytskyi\IdeaProjects\spring-cloud-microservices\config-service\src\main\resources\config
        git:
          uri: https://github.com/rstkhldntsk97/config.git