server:
  port: 9004

spring:
  profiles:
    active: native
  cloud:
    config:
      server:
        native:
          search-locations: file:\\\Users\r.kholodnytskyi\IdeaProjects\spring-cloud-microservices\config-service\src\main\resources\config